name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ✅ Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Step 2: Install and run flake8 for linting
    - name: Run flake8 linter
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 app.py

    # ✅ Step 3: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ✅ Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t hello-world-app .

    # ✅ Step 5: Save the Docker image to a local tarball
    - name: Save Docker image to tar file
      run: |
        mkdir -p docker-output
        docker save hello-world-app -o docker-output/hello-world-app.tar

    # ✅ Step 6: Upload the tarball as a GitHub artifact
    - name: Upload Docker image tarball
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: docker-output/hello-world-app.tar

